services:
  app:
    init: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: docker/Dockerfile.${PROJECT_ENV}
    restart: always
    volumes:
      - ./app:/opt/app:z
    networks:
      - front

networks:
  front:
    driver: bridge
